### ISSUE TITLE
[FEATURE] Validate request from configure screen

### ISSUE THREAD

**Issue by ianwilliams1** [jenkinsci/rest-list-parameter-plugin#10]
**Is your feature request related to a problem? Please describe.**
Unable to validate connection from Config screen.

**Describe the solution you'd like**
When configuring a FreeStyle job, including one that requires authentication, it would be helpful to have a "Validate" or "Test Connection" to ensure the parameters have been set correctly and the response is as expected, prior to saving the job.

When setting a Credential ID for authentication, an immediate error should display (similar to SCM Git client) if authentication fails.

**Describe alternatives you've considered**
The alternative is to save the job, then Build with Parameters, only to see a 4xx message or wrong data and keep fiddling back and forth.

**Additional context**
Refer to behavior of SCM Git client as an example.
Credential + no url == "Please  enter a REST endpoint"
Bad Credential + url == "Failed to connect to ... : <error msg>" 
Credential + url  => quiet success.

Press "Validate" button to get and display response. Not 100% how to present that, but a starting point would be SUCCESS / FAIL / No data

**Comment by h1dden-da3m0n** [comment]
First of all thank you for the feature request and detailed feature description :+1: 

I like the idea and will start to investigate how to best implement this, yet I can't give any estimate on how fast I'll get it out. (:crossed_fingers: soon)

Regardless, I will update this issue with my progress :wink:

**Comment by h1dden-da3m0n** [comment]
Okay, I got the initial part working so far! Now to the full validation :grin:

**Comment by h1dden-da3m0n** [comment]
Just got part two working too. (if you can let me know what u think in the PR) I'll test it a bit more and then merge it.

**Comment by h1dden-da3m0n** [comment]
I'll release 1.1.0 most likely tomorrow (which will feature this).
Thank you for the idea and testing contribution of the feature :+1:

**Comment by ianwilliams1** [comment]
Cool. Thank you for your so prompt response and adding these features! looking forward to trying it out.
I could suggest a few plugins which could use some loving, prompt attention like this!

**Comment by h1dden-da3m0n** [comment]
:grin: Thank you for the laurels, but the main reasons why I was so quick to respond is that I had time and this plugin is rather new (as well as me) in the Jenkins Org/Universe.
I'll try to keep up, yet time has to allow for it.
