### ISSUE TITLE
[BUG] Only global jenkins credentials are passed if REST/Web endpoint  requires authentication

### ISSUE THREAD

**Issue by thejasonfunderburker** [jenkinsci/rest-list-parameter-plugin#154]
English is not my native language so i'll try to give my best explanation
If you set up your Jenkins project in folder and add credentials, that are limited to that folder, even though test configuration works successfully (https://prnt.sc/vr3grXun5SBj) trying to build it will throw 401 error (https://prnt.sc/VCivl-WW9Pdt)
If you add the same credentials globally in jenkins, it will work as expected
https://prnt.sc/i59W2TMGelVK
https://prnt.sc/tZhhvj95oDTq
and building it works with no errors
https://prnt.sc/dMABs5z1lZ5R

**To Reproduce**
1. Go to Jenkins dashboard and create new folder
2. Create a project in this folder
3. Select the option "This project is parameterized" add "REST List Parameter" and fill all the fields according to your rest endpoint, make sure it requires authentication
4. Add credentials limited to that folder (subfolder in my case, but there is no difference) https://prnt.sc/KkgWfYv0epuq
5. Test configuration, everything will work as expected
6. Save project and build it with parameters
7. You will see 401 (unauthorized) error
**Expected behavior**
Credentials are applied, project builds and you receive data from your REST endpoint

**Versions:**
 - Jenkins: [Jenkins 2.360]
 - Plugin: [1.6.2]
 - Browser [tested in firefox, chrome, edge]

**Additional context**

**Comment by h1dden-da3m0n** [comment]
Hello there,

thank you for your bug report and all the supplied detail!
Sounds like I have some duplicated logic where the credential builder is not called with the proper context :thinking:.
I will check that I can reproduce this and hopefully can provide a fix soon :tm:

**Comment by h1dden-da3m0n** [comment]
Okay, I should have fixed my improper credential lookup within #155.

Could you please give the incremental from the PR build a try [rest-list-parameter-1.6.3-rc316.648b_d163506d.hpi](https://ci.jenkins.io/job/Plugins/job/rest-list-parameter-plugin/job/PR-155/1/artifact/io/jenkins/plugins/rest-list-parameter/1.6.3-rc316.648b_d163506d/rest-list-parameter-1.6.3-rc316.648b_d163506d.hpi) (i.e. the hpi file from the [ci.jenkins.io PR Build](https://ci.jenkins.io/job/Plugins/job/rest-list-parameter-plugin/job/PR-155/1/)).
Would appreciate the extra validation before I merge it, as this the second time I had issues with credential lookups (first time #89) I would like to prevent further issues b4 I start rewriting this from the ground up.

**Comment by thejasonfunderburker** [comment]
Hi! Wow, thanks for such a quick fix, I've tested it, everything works like a charm)

**Comment by h1dden-da3m0n** [comment]
happy to hear that :smile: 

I will cut a release soon then, likely Thursday or Friday.

Thank you for reporting and validating the fix!
