### ISSUE TITLE
[FEATURE] - Better presentation / easier selection of response value

### ISSUE THREAD

**Issue by ianwilliams1** [jenkinsci/rest-list-parameter-plugin#20]
**Is your feature request related to a problem? Please describe.**
Selecting build parameter is problematic for large responses. It very difficult to choose desired value.
Our json response is 2000+ values, the response is unordered (or "unknown" - ordered on a field other than the response field).

If many "unordered" values are returned (eg: US state names, but ordered by size), values are all over the place alphabetically in the list. 
eg: Look for Missouri, typing "M" takes you to the first "M", (Massachusetts) but "M", then "I" just moves you to next "I" (Indiana). Typing "M" again takes you to next "M" (Mississippi), skipping "Maine".

**Describe the solution you'd like**
{really two features, but it's tied to the same issue - selectability).

User should be able to select from the drop-down OR simply **start typing; matching values should filter the list**.
A good example is the [ JIRA Search](https://issues.jenkins-ci.org/issues). 
If I type " I should see Missouri and Mississippi to choose from.
Not sure if [Jenkins UI options](https://plugins.jenkins.io/ui-samples-plugin/) readily support that.
_Simplest option may be change `f:textbox` to `f:combobox` ?_

There should be a configuration option to **provide a client-side order transformation**, a "sorted" response (Asc/Desc).
If possible to apply sort as a value expression, it still complicates to combine a criteria AND a sort. Makes for easier usage for both sides as a separate option.

**Describe alternatives you've considered**
Tried experimenting w/Value Expression but have not figured out how to (may be my fault).

**Additional context**
None. Thanks for your efforts and consideration.

**Comment by h1dden-da3m0n** [comment]
Welcome back Ian!

TBH I kind of had this kind of feature (the combobox part at least) in mind even before 1.0, unfortunately back then I was not able to get it to work properly (Jenkins UI DOES provide such a [control](https://reports.jenkins.io/core-taglib/jelly-taglib-ref.html#form:combobox), just that it seemed a bit broken to me IIRC).
Regarding the sorting, that is incredibly easy to add, at least for alphabetical order of the string values, but let me know if that satisfies this feature request or not.

Anyway, I am a bit limited on time in the near future so unsure how fast I can deliver, but I'll try my best and keep u posted.

/Note: If any passing by developer wants to work on this simply say so in this issue! This should prevent us both work on the same code :wink:

**Comment by ianwilliams1** [comment]
To the easy part first...  personally, I believe a sorted order will make the most sense in most occasions (it's just intuitive).

But there are scenarios I can imagine where the user may have intimate knowledge of the returned order OR the query may support sorting directly, so that's the order the user expects them in. That's why I suggest as an option as opposed to "always" sort. Implementing this would go a long way to addressing my usability beef.

As for the combobox option, the (nicer) JIRA example matches any matching substring, whereas the Jenkins use cases of combobox seem to match only from the beginning. That may be the "somewhat broken" impression that we share.

If preferred, split the two parts into separate feature requests (linked) so as to better track implementation.  

sidebar: _As a user of free OSS product, we users appreciate any support provided by developers (and I assume developer appreciates any contributions by the community), so timelines are yours to manage as you choose. We understand [resource  limitations](https://opensource.com/article/20/3/burnout) and even your acknowledgement of issues is great. My biggest beef w/[tfs-plugin](https://github.com/jenkinsci/tfs-plugin), aside from their lack of action in fixing anything is their [complete and utter radio silence on issues](https://issues.jenkins-ci.org/issues/?filter=10230&jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20tfs-plugin). The default assignee remains redsolo who has clearly stated he no longer supports it and it is now a MS respsonbility, so aargh!_

**Comment by h1dden-da3m0n** [comment]
Okay, I split up the request into two parts, as one part is drastically easier for me to realize than the other.
If Jenkins provided a bit more in terms of UI or where a bit more capable or extendable the combo-box part would also be easier, but sadly that is not the case :frowning_face: 
Regardless, I'll try my luck with the `f:combobox` one more time after I have #21 dealt with :wink: 

Thank you Ian for your activity, I really appreciate it :+1:

**Comment by k3rnelpan1c-dev** [comment]
Closing this as the two "sub-tasks" have been closed.
