### ISSUE TITLE
[FEATURE] Give the user a option to alphabetically sort values

### ISSUE THREAD

**Issue by h1dden-da3m0n** [jenkinsci/rest-list-parameter-plugin#21]
**Is your feature request related to a problem? Please describe.**

This issue is meant to track any progress made on providing a option to allow the user to alphabetically sort the values returned by the REST endpoint, whilst still supporting endpoints that already return the values in order (natively or via request param).

This issue is connected and a sub task of #20  

**Describe the solution you'd like**

A option in the "advanced" configuration of the parameter configuration allowing the user to select ordering/sorting.

* None - Order of values is taken from the order they arrive in
* AtoZ - Simple alphabetical order
* ZtoA - Reverse alphabetical order

**Describe alternatives you've considered**

There isn't really an alternative to this functionality, besides having a REST endpoint that can be told to sort the returns values, which requires the REST endpoints support.

**Additional context**

N/A

**Comment by ianwilliams1** [comment]
I'd suggest the terminology as:
None - Order of values is taken from the order they arrive in
˄ - Ascending
˅ - Descending

That way the description makes sense, even if it's a list including numeric values.

**Comment by h1dden-da3m0n** [comment]
> I'd suggest the terminology as:
> None - Order of values is taken from the order they arrive in
> ˄ - Ascending
> ˅ - Descending
> 
> That way the description makes sense, even if it's a list including numeric values.

Fair, though I might use NONE, ASC and DSC, as I most likely will use a Rnum to realize this and Jenkins UI having a native render control and ease of use in the JobDSL.
