### ISSUE TITLE
[BUG] Only Java level Web proxy settings apply

### ISSUE THREAD

**Issue by h1dden-da3m0n** [jenkinsci/rest-list-parameter-plugin#27]
**Describe the bug**

For a Jenkins plugin it is to be expected that the Jenkins set web proxy should be enough to call out (if the proxy allows for that), unfortunately I missed the logic to actually account for that :worried:.
Currently the only way to have the plugin work is to have the Jenkins Java war run with the Java global proxy settings.

```
-Dhttp.proxyHost=proxy.server.com
-Dhttp.proxyPort=80

-Dhttps.proxyHost=proxy.server.com
-Dhttps.proxyPort=80
```

**To Reproduce**

1. Have your Jenkins run in a http_proxy environment
2. create a new Job
3. add a Rest-List-Paramert
4. See host resolution error

**Expected behavior**

The plugin should respect the Jenkins configured http proxy (this can be set in the 'Manage Jenkins' > 'Plugin Manager'  > 'Advanced' section)

**Versions (please complete the following information):**
 - Jenkins: 2.249.2
 - Plugin: 1.1.0
 - Browser: Firefox, Chrome (any really)

**Additional context**

N/A

**Comment by h1dden-da3m0n** [comment]
I already know how to fix this thanks to the github-plugin using the same HTTP library and them already supporting this ([see here](https://github.com/jenkinsci/github-plugin/blob/e75ef03f4a992c16dd60ecefa2d82ca667e9b258/src/main/java/org/jenkinsci/plugins/github/internal/GitHubLoginFunction.java#L87)).

I will most likely wait with a fix for this till 1.2.0, since I am already touching the OKHttp (the HTTP library used) connection and client there and can incorporate this fix with it.

Should someone however face this BUG and need a immediate fix, then let me know or set the global Java HTTP proxy properties for now.

**Comment by jamesnswithers** [comment]
For our use case fixing this 'bug' would hurt us as we set the Plugin Manager proxy so we can reach out to the internet for plugin updates however all of the webservices we fetch data from are internal which are not available through our corporate proxy. Food for thought as i'm not sure how common place this.

**Comment by h1dden-da3m0n** [comment]
Hi @jamesnswithers!

Thank you for the comment, and yes this is common to have your proxy to just allow access to the outside world.
However, then there is the field "no proxy" that allows for wildcard definitions.
Say you have your local services like the following:
* gitea.local.lan
* nexus.local.lan
* service.local.lan

then you can add this to the no proxy field and none of those addresses would get sent to the proxy:
* *.local.lan

NOTE: I would be not alone to "solve" this issue this way, it is common practice among plugins, just that I have overlooked this in my initial implementation xD

(but let me know if that still affects your use-case, then i can add a global config to disable this behavior :wink: )
