### ISSUE TITLE
[BUG] User scoped credentials cannot be used

### ISSUE THREAD

**Issue by jimmyh85** [jenkinsci/rest-list-parameter-plugin#89]
**Describe the bug**
Scoped credentials cannot be used. 

**To Reproduce**
1. Create a new Jenkins folder and within this new folder a new scoped credential
2. In the credential dropdown of the plugin choose the above created credential
3. See error

**Expected behavior**
Scoped credentials can be used as well

**Screenshots**
![credentials_error](https://user-images.githubusercontent.com/19154747/131800620-0ef03334-80cc-49cb-a45e-da35361576f9.png)

**Versions (please complete the following information):**
 - Jenkins: [2.249.1]
 - Plugin: [1.2.2]
 - Browser [firefox, chrome]

**Additional context**

A possible solution could look like this (not production ready code though)
```groovy
import com.cloudbees.plugins.credentials.Credentials

Set<Credentials> allCredentials = new HashSet<Credentials>();

// Get credentials from the root scope
def creds = com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(
      com.cloudbees.plugins.credentials.Credentials.class
);

allCredentials.addAll(creds)

// Get credentials from the user scopes respectively folders
Jenkins.instance.getAllItems(com.cloudbees.hudson.plugins.folder.Folder.class).each{ folder ->
 creds = com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(
      com.cloudbees.plugins.credentials.Credentials.class, folder)
  allCredentials.addAll(creds)
}
```

**Comment by h1dden-da3m0n** [comment]
Hi jimmy,

Thank you for this bug-report. I should have some time this weekend to look into this and see what I can do.
The current credentials selection code was directly taken from the Credentials Plugin docs IIRC so this is interesting :thinking:

**Comment by h1dden-da3m0n** [comment]
@jimmyh85 

okay I take full responsibility for messing that one up :man_facepalming: #90 should fix this for you, so be on the lookout for v1.4.2 :wink:

**Comment by h1dden-da3m0n** [comment]
Okay I intended to release today but apparently the JeninsCI infra has some issue where despite proper setup cant upload to Artifactory anymore :expressionless: 

I will try my best to get 1.4.2 published there ASAP but in the mean time the GH Release is the only place where the .hip was successfully deployed to  :confused:

**Comment by jimmyh85** [comment]
Hi @h1dden-da3m0n ,
thank you very much for the quick fix. Awesome job 👍

**Comment by h1dden-da3m0n** [comment]
was able to finish  the 1.4.2 release today and it should now be available from the Jenkins repo :tada:
